# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: in_sdk.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import in_sdk_header_pb2 as in__sdk__header__pb2
import in_sdk_body_pb2 as in__sdk__body__pb2
import in_sdk_footer_pb2 as in__sdk__footer__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='in_sdk.proto',
  package='insider.sdk',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cin_sdk.proto\x12\x0binsider.sdk\x1a\x13in_sdk_header.proto\x1a\x11in_sdk_body.proto\x1a\x13in_sdk_footer.proto\"p\n\x03Sdk\x12#\n\x06header\x18\x01 \x01(\x0b\x32\x13.insider.sdk.Header\x12\x1f\n\x04\x62ody\x18\x02 \x01(\x0b\x32\x11.insider.sdk.Body\x12#\n\x06\x66ooter\x18\x03 \x01(\x0b\x32\x13.insider.sdk.Footerb\x06proto3')
  ,
  dependencies=[in__sdk__header__pb2.DESCRIPTOR,in__sdk__body__pb2.DESCRIPTOR,in__sdk__footer__pb2.DESCRIPTOR,])




_SDK = _descriptor.Descriptor(
  name='Sdk',
  full_name='insider.sdk.Sdk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='insider.sdk.Sdk.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='insider.sdk.Sdk.body', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='footer', full_name='insider.sdk.Sdk.footer', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=202,
)

_SDK.fields_by_name['header'].message_type = in__sdk__header__pb2._HEADER
_SDK.fields_by_name['body'].message_type = in__sdk__body__pb2._BODY
_SDK.fields_by_name['footer'].message_type = in__sdk__footer__pb2._FOOTER
DESCRIPTOR.message_types_by_name['Sdk'] = _SDK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Sdk = _reflection.GeneratedProtocolMessageType('Sdk', (_message.Message,), {
  'DESCRIPTOR' : _SDK,
  '__module__' : 'in_sdk_pb2'
  # @@protoc_insertion_point(class_scope:insider.sdk.Sdk)
  })
_sym_db.RegisterMessage(Sdk)


# @@protoc_insertion_point(module_scope)
