// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: in_sdk_body_appmodule.proto

#include "in_sdk_body_appmodule.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_in_5fsdk_5fbody_5fappmodule_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_AppModuleBaseInfo_in_5fsdk_5fbody_5fappmodule_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_in_5fsdk_5fbody_5fappmodule_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_AppModuleCoutInfo_in_5fsdk_5fbody_5fappmodule_2eproto;
namespace insider {
namespace sdk {
class AppModuleBaseInfoDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<AppModuleBaseInfo> _instance;
} _AppModuleBaseInfo_default_instance_;
class AppModuleCoutInfoDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<AppModuleCoutInfo> _instance;
} _AppModuleCoutInfo_default_instance_;
class AppModuleCoutInfoListDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<AppModuleCoutInfoList> _instance;
} _AppModuleCoutInfoList_default_instance_;
}  // namespace sdk
}  // namespace insider
static void InitDefaultsscc_info_AppModuleBaseInfo_in_5fsdk_5fbody_5fappmodule_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::insider::sdk::_AppModuleBaseInfo_default_instance_;
    new (ptr) ::insider::sdk::AppModuleBaseInfo();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::insider::sdk::AppModuleBaseInfo::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_AppModuleBaseInfo_in_5fsdk_5fbody_5fappmodule_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_AppModuleBaseInfo_in_5fsdk_5fbody_5fappmodule_2eproto}, {}};

static void InitDefaultsscc_info_AppModuleCoutInfo_in_5fsdk_5fbody_5fappmodule_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::insider::sdk::_AppModuleCoutInfo_default_instance_;
    new (ptr) ::insider::sdk::AppModuleCoutInfo();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::insider::sdk::AppModuleCoutInfo::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_AppModuleCoutInfo_in_5fsdk_5fbody_5fappmodule_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_AppModuleCoutInfo_in_5fsdk_5fbody_5fappmodule_2eproto}, {
      &scc_info_AppModuleBaseInfo_in_5fsdk_5fbody_5fappmodule_2eproto.base,}};

static void InitDefaultsscc_info_AppModuleCoutInfoList_in_5fsdk_5fbody_5fappmodule_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::insider::sdk::_AppModuleCoutInfoList_default_instance_;
    new (ptr) ::insider::sdk::AppModuleCoutInfoList();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::insider::sdk::AppModuleCoutInfoList::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_AppModuleCoutInfoList_in_5fsdk_5fbody_5fappmodule_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_AppModuleCoutInfoList_in_5fsdk_5fbody_5fappmodule_2eproto}, {
      &scc_info_AppModuleCoutInfo_in_5fsdk_5fbody_5fappmodule_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_in_5fsdk_5fbody_5fappmodule_2eproto[3];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_in_5fsdk_5fbody_5fappmodule_2eproto[3];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_in_5fsdk_5fbody_5fappmodule_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_in_5fsdk_5fbody_5fappmodule_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::insider::sdk::AppModuleBaseInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::insider::sdk::AppModuleBaseInfo, name_),
  PROTOBUF_FIELD_OFFSET(::insider::sdk::AppModuleBaseInfo, enable_),
  PROTOBUF_FIELD_OFFSET(::insider::sdk::AppModuleBaseInfo, state_),
  PROTOBUF_FIELD_OFFSET(::insider::sdk::AppModuleBaseInfo, permission_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::insider::sdk::AppModuleCoutInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::insider::sdk::AppModuleCoutInfo, id_),
  PROTOBUF_FIELD_OFFSET(::insider::sdk::AppModuleCoutInfo, run_state_),
  PROTOBUF_FIELD_OFFSET(::insider::sdk::AppModuleCoutInfo, base_info_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::insider::sdk::AppModuleCoutInfoList, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::insider::sdk::AppModuleCoutInfoList, app_modules_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::insider::sdk::AppModuleBaseInfo)},
  { 9, -1, sizeof(::insider::sdk::AppModuleCoutInfo)},
  { 17, -1, sizeof(::insider::sdk::AppModuleCoutInfoList)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::insider::sdk::_AppModuleBaseInfo_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::insider::sdk::_AppModuleCoutInfo_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::insider::sdk::_AppModuleCoutInfoList_default_instance_),
};

const char descriptor_table_protodef_in_5fsdk_5fbody_5fappmodule_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\033in_sdk_body_appmodule.proto\022\013insider.s"
  "dk\"\226\001\n\021AppModuleBaseInfo\022\014\n\004name\030\001 \001(\t\022\016"
  "\n\006enable\030\002 \001(\010\022*\n\005state\030\003 \001(\0162\033.insider."
  "sdk.AppModuleState\0227\n\npermission\030\004 \001(\0162#"
  ".insider.sdk.AppModuleCfgPermission\"\205\001\n\021"
  "AppModuleCoutInfo\022\n\n\002id\030\001 \001(\r\0221\n\trun_sta"
  "te\030\002 \001(\0162\036.insider.sdk.AppModuleRunState"
  "\0221\n\tbase_info\030\003 \001(\0132\036.insider.sdk.AppMod"
  "uleBaseInfo\"L\n\025AppModuleCoutInfoList\0223\n\013"
  "app_modules\030\001 \003(\0132\036.insider.sdk.AppModul"
  "eCoutInfo*p\n\016AppModuleState\022\025\n\021E_APP_MOD"
  "ULE_IDLE\020\000\022\025\n\021E_APP_MODULE_INIT\020\001\022\032\n\026E_A"
  "PP_MODULE_INSTALLED\020\002\022\024\n\020E_APP_MODULE_BA"
  "D\020\003*m\n\021AppModuleRunState\022\032\n\026E_APP_MODULE"
  "_RUN_ST_OK\020\000\022\033\n\027E_APP_MODULE_RUN_ST_ERR\020"
  "\001\022\037\n\033E_APP_MODULE_RUN_ST_UNKNOWN\020\002*k\n\026Ap"
  "pModuleCfgPermission\022&\n\"E_APP_MODULE_CFG"
  "_PERMISSION_ENABLE\020\000\022)\n%E_APP_MODULE_CFG"
  "_PERMISSION_DISENABLE\020\001b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_in_5fsdk_5fbody_5fappmodule_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_in_5fsdk_5fbody_5fappmodule_2eproto_sccs[3] = {
  &scc_info_AppModuleBaseInfo_in_5fsdk_5fbody_5fappmodule_2eproto.base,
  &scc_info_AppModuleCoutInfo_in_5fsdk_5fbody_5fappmodule_2eproto.base,
  &scc_info_AppModuleCoutInfoList_in_5fsdk_5fbody_5fappmodule_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_in_5fsdk_5fbody_5fappmodule_2eproto_once;
static bool descriptor_table_in_5fsdk_5fbody_5fappmodule_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_in_5fsdk_5fbody_5fappmodule_2eproto = {
  &descriptor_table_in_5fsdk_5fbody_5fappmodule_2eproto_initialized, descriptor_table_protodef_in_5fsdk_5fbody_5fappmodule_2eproto, "in_sdk_body_appmodule.proto", 751,
  &descriptor_table_in_5fsdk_5fbody_5fappmodule_2eproto_once, descriptor_table_in_5fsdk_5fbody_5fappmodule_2eproto_sccs, descriptor_table_in_5fsdk_5fbody_5fappmodule_2eproto_deps, 3, 0,
  schemas, file_default_instances, TableStruct_in_5fsdk_5fbody_5fappmodule_2eproto::offsets,
  file_level_metadata_in_5fsdk_5fbody_5fappmodule_2eproto, 3, file_level_enum_descriptors_in_5fsdk_5fbody_5fappmodule_2eproto, file_level_service_descriptors_in_5fsdk_5fbody_5fappmodule_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_in_5fsdk_5fbody_5fappmodule_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_in_5fsdk_5fbody_5fappmodule_2eproto), true);
namespace insider {
namespace sdk {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AppModuleState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_in_5fsdk_5fbody_5fappmodule_2eproto);
  return file_level_enum_descriptors_in_5fsdk_5fbody_5fappmodule_2eproto[0];
}
bool AppModuleState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AppModuleRunState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_in_5fsdk_5fbody_5fappmodule_2eproto);
  return file_level_enum_descriptors_in_5fsdk_5fbody_5fappmodule_2eproto[1];
}
bool AppModuleRunState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AppModuleCfgPermission_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_in_5fsdk_5fbody_5fappmodule_2eproto);
  return file_level_enum_descriptors_in_5fsdk_5fbody_5fappmodule_2eproto[2];
}
bool AppModuleCfgPermission_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void AppModuleBaseInfo::InitAsDefaultInstance() {
}
class AppModuleBaseInfo::_Internal {
 public:
};

AppModuleBaseInfo::AppModuleBaseInfo()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:insider.sdk.AppModuleBaseInfo)
}
AppModuleBaseInfo::AppModuleBaseInfo(const AppModuleBaseInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_name().empty()) {
    name_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  ::memcpy(&enable_, &from.enable_,
    static_cast<size_t>(reinterpret_cast<char*>(&permission_) -
    reinterpret_cast<char*>(&enable_)) + sizeof(permission_));
  // @@protoc_insertion_point(copy_constructor:insider.sdk.AppModuleBaseInfo)
}

void AppModuleBaseInfo::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_AppModuleBaseInfo_in_5fsdk_5fbody_5fappmodule_2eproto.base);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&enable_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&permission_) -
      reinterpret_cast<char*>(&enable_)) + sizeof(permission_));
}

AppModuleBaseInfo::~AppModuleBaseInfo() {
  // @@protoc_insertion_point(destructor:insider.sdk.AppModuleBaseInfo)
  SharedDtor();
}

void AppModuleBaseInfo::SharedDtor() {
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void AppModuleBaseInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const AppModuleBaseInfo& AppModuleBaseInfo::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_AppModuleBaseInfo_in_5fsdk_5fbody_5fappmodule_2eproto.base);
  return *internal_default_instance();
}


void AppModuleBaseInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:insider.sdk.AppModuleBaseInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&enable_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&permission_) -
      reinterpret_cast<char*>(&enable_)) + sizeof(permission_));
  _internal_metadata_.Clear();
}

const char* AppModuleBaseInfo::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParserUTF8(_internal_mutable_name(), ptr, ctx, "insider.sdk.AppModuleBaseInfo.name");
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool enable = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          enable_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .insider.sdk.AppModuleState state = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
          _internal_set_state(static_cast<::insider::sdk::AppModuleState>(val));
        } else goto handle_unusual;
        continue;
      // .insider.sdk.AppModuleCfgPermission permission = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
          _internal_set_permission(static_cast<::insider::sdk::AppModuleCfgPermission>(val));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* AppModuleBaseInfo::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:insider.sdk.AppModuleBaseInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "insider.sdk.AppModuleBaseInfo.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // bool enable = 2;
  if (this->enable() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(2, this->_internal_enable(), target);
  }

  // .insider.sdk.AppModuleState state = 3;
  if (this->state() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      3, this->_internal_state(), target);
  }

  // .insider.sdk.AppModuleCfgPermission permission = 4;
  if (this->permission() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      4, this->_internal_permission(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:insider.sdk.AppModuleBaseInfo)
  return target;
}

size_t AppModuleBaseInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:insider.sdk.AppModuleBaseInfo)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // bool enable = 2;
  if (this->enable() != 0) {
    total_size += 1 + 1;
  }

  // .insider.sdk.AppModuleState state = 3;
  if (this->state() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_state());
  }

  // .insider.sdk.AppModuleCfgPermission permission = 4;
  if (this->permission() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_permission());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AppModuleBaseInfo::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:insider.sdk.AppModuleBaseInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const AppModuleBaseInfo* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<AppModuleBaseInfo>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:insider.sdk.AppModuleBaseInfo)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:insider.sdk.AppModuleBaseInfo)
    MergeFrom(*source);
  }
}

void AppModuleBaseInfo::MergeFrom(const AppModuleBaseInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:insider.sdk.AppModuleBaseInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.enable() != 0) {
    _internal_set_enable(from._internal_enable());
  }
  if (from.state() != 0) {
    _internal_set_state(from._internal_state());
  }
  if (from.permission() != 0) {
    _internal_set_permission(from._internal_permission());
  }
}

void AppModuleBaseInfo::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:insider.sdk.AppModuleBaseInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AppModuleBaseInfo::CopyFrom(const AppModuleBaseInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:insider.sdk.AppModuleBaseInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AppModuleBaseInfo::IsInitialized() const {
  return true;
}

void AppModuleBaseInfo::InternalSwap(AppModuleBaseInfo* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  name_.Swap(&other->name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(enable_, other->enable_);
  swap(state_, other->state_);
  swap(permission_, other->permission_);
}

::PROTOBUF_NAMESPACE_ID::Metadata AppModuleBaseInfo::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void AppModuleCoutInfo::InitAsDefaultInstance() {
  ::insider::sdk::_AppModuleCoutInfo_default_instance_._instance.get_mutable()->base_info_ = const_cast< ::insider::sdk::AppModuleBaseInfo*>(
      ::insider::sdk::AppModuleBaseInfo::internal_default_instance());
}
class AppModuleCoutInfo::_Internal {
 public:
  static const ::insider::sdk::AppModuleBaseInfo& base_info(const AppModuleCoutInfo* msg);
};

const ::insider::sdk::AppModuleBaseInfo&
AppModuleCoutInfo::_Internal::base_info(const AppModuleCoutInfo* msg) {
  return *msg->base_info_;
}
AppModuleCoutInfo::AppModuleCoutInfo()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:insider.sdk.AppModuleCoutInfo)
}
AppModuleCoutInfo::AppModuleCoutInfo(const AppModuleCoutInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from._internal_has_base_info()) {
    base_info_ = new ::insider::sdk::AppModuleBaseInfo(*from.base_info_);
  } else {
    base_info_ = nullptr;
  }
  ::memcpy(&id_, &from.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&run_state_) -
    reinterpret_cast<char*>(&id_)) + sizeof(run_state_));
  // @@protoc_insertion_point(copy_constructor:insider.sdk.AppModuleCoutInfo)
}

void AppModuleCoutInfo::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_AppModuleCoutInfo_in_5fsdk_5fbody_5fappmodule_2eproto.base);
  ::memset(&base_info_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&run_state_) -
      reinterpret_cast<char*>(&base_info_)) + sizeof(run_state_));
}

AppModuleCoutInfo::~AppModuleCoutInfo() {
  // @@protoc_insertion_point(destructor:insider.sdk.AppModuleCoutInfo)
  SharedDtor();
}

void AppModuleCoutInfo::SharedDtor() {
  if (this != internal_default_instance()) delete base_info_;
}

void AppModuleCoutInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const AppModuleCoutInfo& AppModuleCoutInfo::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_AppModuleCoutInfo_in_5fsdk_5fbody_5fappmodule_2eproto.base);
  return *internal_default_instance();
}


void AppModuleCoutInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:insider.sdk.AppModuleCoutInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == nullptr && base_info_ != nullptr) {
    delete base_info_;
  }
  base_info_ = nullptr;
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&run_state_) -
      reinterpret_cast<char*>(&id_)) + sizeof(run_state_));
  _internal_metadata_.Clear();
}

const char* AppModuleCoutInfo::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .insider.sdk.AppModuleRunState run_state = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
          _internal_set_run_state(static_cast<::insider::sdk::AppModuleRunState>(val));
        } else goto handle_unusual;
        continue;
      // .insider.sdk.AppModuleBaseInfo base_info = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_base_info(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* AppModuleCoutInfo::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:insider.sdk.AppModuleCoutInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 id = 1;
  if (this->id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_id(), target);
  }

  // .insider.sdk.AppModuleRunState run_state = 2;
  if (this->run_state() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      2, this->_internal_run_state(), target);
  }

  // .insider.sdk.AppModuleBaseInfo base_info = 3;
  if (this->has_base_info()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, _Internal::base_info(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:insider.sdk.AppModuleCoutInfo)
  return target;
}

size_t AppModuleCoutInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:insider.sdk.AppModuleCoutInfo)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .insider.sdk.AppModuleBaseInfo base_info = 3;
  if (this->has_base_info()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *base_info_);
  }

  // uint32 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_id());
  }

  // .insider.sdk.AppModuleRunState run_state = 2;
  if (this->run_state() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_run_state());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AppModuleCoutInfo::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:insider.sdk.AppModuleCoutInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const AppModuleCoutInfo* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<AppModuleCoutInfo>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:insider.sdk.AppModuleCoutInfo)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:insider.sdk.AppModuleCoutInfo)
    MergeFrom(*source);
  }
}

void AppModuleCoutInfo::MergeFrom(const AppModuleCoutInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:insider.sdk.AppModuleCoutInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_base_info()) {
    _internal_mutable_base_info()->::insider::sdk::AppModuleBaseInfo::MergeFrom(from._internal_base_info());
  }
  if (from.id() != 0) {
    _internal_set_id(from._internal_id());
  }
  if (from.run_state() != 0) {
    _internal_set_run_state(from._internal_run_state());
  }
}

void AppModuleCoutInfo::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:insider.sdk.AppModuleCoutInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AppModuleCoutInfo::CopyFrom(const AppModuleCoutInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:insider.sdk.AppModuleCoutInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AppModuleCoutInfo::IsInitialized() const {
  return true;
}

void AppModuleCoutInfo::InternalSwap(AppModuleCoutInfo* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(base_info_, other->base_info_);
  swap(id_, other->id_);
  swap(run_state_, other->run_state_);
}

::PROTOBUF_NAMESPACE_ID::Metadata AppModuleCoutInfo::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void AppModuleCoutInfoList::InitAsDefaultInstance() {
}
class AppModuleCoutInfoList::_Internal {
 public:
};

AppModuleCoutInfoList::AppModuleCoutInfoList()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:insider.sdk.AppModuleCoutInfoList)
}
AppModuleCoutInfoList::AppModuleCoutInfoList(const AppModuleCoutInfoList& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      app_modules_(from.app_modules_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:insider.sdk.AppModuleCoutInfoList)
}

void AppModuleCoutInfoList::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_AppModuleCoutInfoList_in_5fsdk_5fbody_5fappmodule_2eproto.base);
}

AppModuleCoutInfoList::~AppModuleCoutInfoList() {
  // @@protoc_insertion_point(destructor:insider.sdk.AppModuleCoutInfoList)
  SharedDtor();
}

void AppModuleCoutInfoList::SharedDtor() {
}

void AppModuleCoutInfoList::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const AppModuleCoutInfoList& AppModuleCoutInfoList::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_AppModuleCoutInfoList_in_5fsdk_5fbody_5fappmodule_2eproto.base);
  return *internal_default_instance();
}


void AppModuleCoutInfoList::Clear() {
// @@protoc_insertion_point(message_clear_start:insider.sdk.AppModuleCoutInfoList)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  app_modules_.Clear();
  _internal_metadata_.Clear();
}

const char* AppModuleCoutInfoList::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated .insider.sdk.AppModuleCoutInfo app_modules = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_app_modules(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* AppModuleCoutInfoList::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:insider.sdk.AppModuleCoutInfoList)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .insider.sdk.AppModuleCoutInfo app_modules = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_app_modules_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(1, this->_internal_app_modules(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:insider.sdk.AppModuleCoutInfoList)
  return target;
}

size_t AppModuleCoutInfoList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:insider.sdk.AppModuleCoutInfoList)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .insider.sdk.AppModuleCoutInfo app_modules = 1;
  total_size += 1UL * this->_internal_app_modules_size();
  for (const auto& msg : this->app_modules_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AppModuleCoutInfoList::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:insider.sdk.AppModuleCoutInfoList)
  GOOGLE_DCHECK_NE(&from, this);
  const AppModuleCoutInfoList* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<AppModuleCoutInfoList>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:insider.sdk.AppModuleCoutInfoList)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:insider.sdk.AppModuleCoutInfoList)
    MergeFrom(*source);
  }
}

void AppModuleCoutInfoList::MergeFrom(const AppModuleCoutInfoList& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:insider.sdk.AppModuleCoutInfoList)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  app_modules_.MergeFrom(from.app_modules_);
}

void AppModuleCoutInfoList::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:insider.sdk.AppModuleCoutInfoList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AppModuleCoutInfoList::CopyFrom(const AppModuleCoutInfoList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:insider.sdk.AppModuleCoutInfoList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AppModuleCoutInfoList::IsInitialized() const {
  return true;
}

void AppModuleCoutInfoList::InternalSwap(AppModuleCoutInfoList* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  app_modules_.InternalSwap(&other->app_modules_);
}

::PROTOBUF_NAMESPACE_ID::Metadata AppModuleCoutInfoList::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace sdk
}  // namespace insider
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::insider::sdk::AppModuleBaseInfo* Arena::CreateMaybeMessage< ::insider::sdk::AppModuleBaseInfo >(Arena* arena) {
  return Arena::CreateInternal< ::insider::sdk::AppModuleBaseInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::insider::sdk::AppModuleCoutInfo* Arena::CreateMaybeMessage< ::insider::sdk::AppModuleCoutInfo >(Arena* arena) {
  return Arena::CreateInternal< ::insider::sdk::AppModuleCoutInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::insider::sdk::AppModuleCoutInfoList* Arena::CreateMaybeMessage< ::insider::sdk::AppModuleCoutInfoList >(Arena* arena) {
  return Arena::CreateInternal< ::insider::sdk::AppModuleCoutInfoList >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
