// source: in_sdk_body.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.insider.sdk.UserInfo');
goog.provide('proto.insider.sdk.UserInfo.UserType');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.insider.sdk.User');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.insider.sdk.UserInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.insider.sdk.UserInfo.repeatedFields_, null);
};
goog.inherits(proto.insider.sdk.UserInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.insider.sdk.UserInfo.displayName = 'proto.insider.sdk.UserInfo';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.insider.sdk.UserInfo.repeatedFields_ = [2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.insider.sdk.UserInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.insider.sdk.UserInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.insider.sdk.UserInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.insider.sdk.UserInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    userType: jspb.Message.getFieldWithDefault(msg, 1, 0),
    userList: jspb.Message.toObjectList(msg.getUserList(),
    proto.insider.sdk.User.toObject, includeInstance),
    tokenList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.insider.sdk.UserInfo}
 */
proto.insider.sdk.UserInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.insider.sdk.UserInfo;
  return proto.insider.sdk.UserInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.insider.sdk.UserInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.insider.sdk.UserInfo}
 */
proto.insider.sdk.UserInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.insider.sdk.UserInfo.UserType} */ (reader.readEnum());
      msg.setUserType(value);
      break;
    case 2:
      var value = new proto.insider.sdk.User;
      reader.readMessage(value,proto.insider.sdk.User.deserializeBinaryFromReader);
      msg.addUser(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addToken(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.insider.sdk.UserInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.insider.sdk.UserInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.insider.sdk.UserInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.insider.sdk.UserInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getUserList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.insider.sdk.User.serializeBinaryToWriter
    );
  }
  f = message.getTokenList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.insider.sdk.UserInfo.UserType = {
  U_LOGIN: 0,
  U_LOGOUT: 1,
  U_VERI: 2
};

/**
 * optional UserType user_type = 1;
 * @return {!proto.insider.sdk.UserInfo.UserType}
 */
proto.insider.sdk.UserInfo.prototype.getUserType = function() {
  return /** @type {!proto.insider.sdk.UserInfo.UserType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.insider.sdk.UserInfo.UserType} value
 * @return {!proto.insider.sdk.UserInfo} returns this
 */
proto.insider.sdk.UserInfo.prototype.setUserType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * repeated User user = 2;
 * @return {!Array<!proto.insider.sdk.User>}
 */
proto.insider.sdk.UserInfo.prototype.getUserList = function() {
  return /** @type{!Array<!proto.insider.sdk.User>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.insider.sdk.User, 2));
};


/**
 * @param {!Array<!proto.insider.sdk.User>} value
 * @return {!proto.insider.sdk.UserInfo} returns this
*/
proto.insider.sdk.UserInfo.prototype.setUserList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.insider.sdk.User=} opt_value
 * @param {number=} opt_index
 * @return {!proto.insider.sdk.User}
 */
proto.insider.sdk.UserInfo.prototype.addUser = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.insider.sdk.User, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.insider.sdk.UserInfo} returns this
 */
proto.insider.sdk.UserInfo.prototype.clearUserList = function() {
  return this.setUserList([]);
};


/**
 * repeated string token = 3;
 * @return {!Array<string>}
 */
proto.insider.sdk.UserInfo.prototype.getTokenList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.insider.sdk.UserInfo} returns this
 */
proto.insider.sdk.UserInfo.prototype.setTokenList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.insider.sdk.UserInfo} returns this
 */
proto.insider.sdk.UserInfo.prototype.addToken = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.insider.sdk.UserInfo} returns this
 */
proto.insider.sdk.UserInfo.prototype.clearTokenList = function() {
  return this.setTokenList([]);
};


